extensions:
    pim-job-instance-sylake-sylakim-show:
        module: pim/form/common/edit-form

    pim-job-instance-sylake-sylakim-show-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-sylake-sylakim-show
        targetZone: content
        position: 100

    pim-job-instance-sylake-sylakim-show-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-sylake-sylakim-show-tabs
        aclResourceId: pim_importexport_export_profile_property_show
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-sylake-sylakim-show-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-sylake-sylakim-show-tabs
        aclResourceId: pim_importexport_export_profile_content_show
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-sylake-sylakim-show-history:
        module: pim/common/tab/history
        parent: pim-job-instance-sylake-sylakim-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pim-job-instance-sylake-sylakim-show-properties-code:
            module: pim/job/common/edit/field/text
            parent: pim-job-instance-sylake-sylakim-show-properties
            position: 100
            targetZone: properties
            config:
                fieldCode: code
                label: pim_enrich.form.job_instance.tab.properties.code.title
                readOnly: true

    pim-job-instance-sylake-sylakim-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-sylakim-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    pim-job-instance-sylake-sylakim-show-properties-api-url:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-sylakim-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.api_url
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.api_url.title
            tooltip: pim_enrich.form.job_instance.tab.properties.api_url.help

    pim-job-instance-sylake-sylakim-show-properties-api-public-id:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-sylakim-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.api_public_id
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.api_public_id.title
            tooltip: pim_enrich.form.job_instance.tab.properties.api_public_id.help

    pim-job-instance-sylake-sylakim-show-properties-api-secret:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-sylakim-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.api_secret
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.api_secret.title
            tooltip: pim_enrich.form.job_instance.tab.properties.api_secret.help

    pim-job-instance-sylake-sylakim-show-properties-admin-login:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-sylakim-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.admin_login
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.admin_login.title
            tooltip: pim_enrich.form.job_instance.tab.properties.admin_login.help

    pim-job-instance-sylake-sylakim-show-properties-admin-password:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-sylakim-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.admin_password
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.admin_password.title
            tooltip: pim_enrich.form.job_instance.tab.properties.admin_password.help

    pim-job-instance-sylake-sylakim-show-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-sylake-sylakim-show-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-sylake-sylakim-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-sylake-sylakim-show
        targetZone: title
        position: 100

    pim-job-instance-sylake-sylakim-show-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-sylake-sylakim-show
        targetZone: meta
        position: 100

    pim-job-instance-sylake-sylakim-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-sylake-sylakim-show
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-sylake-sylakim-show-content-readonly:
        module: pim/job/product/edit/content/readonly
        parent: pim-job-instance-sylake-sylakim-show-content

    pim-job-instance-sylake-sylakim-show-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: pim-job-instance-sylake-sylakim-show-content-data

    pim-job-instance-sylake-sylakim-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-sylake-sylakim-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    pim-job-instance-sylake-sylakim-show-launch:
        module: pim/job/common/edit/launch
        parent: pim-job-instance-sylake-sylakim-show
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code
